package id.co.integrapratama.sdk.feature_sale.domain

data class TransactionRecord(
    val invoice: String,
    val invoiceDate: String,
    val issuerID: String,
    val issuerName: String,
    val saleType: String,
    val batchNo: String,
    val authCode: String,
    val amount: Long = 0,
    val payID: String,
    val pan: String = "",
    val mID: String,
    val tID: String,
    val printFormats: String,
    val refNo: String,
    val txnTypeId: String,
    val programName: String? = "",
    val cardExpiry: String? = "",
    val cardAID: String? = "",
    val cardAppName: String? = "",
    val customerName: String? = "",
    val currencyCode: String? = "",
    val tVRData: String? = "",
    val tSIData: String? = "",
    val txnCatCode: String? = "",
    val txnCert: String? = "",
    val stan: String? = "",
    val maskedCardNo: String? = "",
    val insertModeCode: String? = "",
    val rrNo: String,
    val txnStatus: String,
    val cardType: String = "",
    val cardTypeCode: String = "",
    val acquiringBank: String,
    val secureData: String,
    val posEntryMode: String,
    val tipAmount: Long = 0,
    val cashAMT: Long = 0,
    val feeAmount: Long = 0,
    val refTxnTypeId: String = "",
    val tenure: String = "",
    val bankTID: String,
    val bankMID: String,
    val cashierID: String = "",
    val terminalCapability: String = "",
    val jsonReq: String = "",
    val jsonResp: String = "",
    val eMIAmount: Long = 0L,
    val redeemAmount: Long = 0L,
    val pinBlock: String = "",
    val isTxnActive: Boolean = false,
    val isTxnVoid: Boolean = false,
    val isVoidApplicable: Boolean = false,
    val isLoyaltyVoid: Boolean = false,
    val loyaltyData: String = "",
    val panSeq: String = "",
    val iccData: String = "",
    val responseCode: String = "",
    val mti: String = "",
    val jsonReceipt: String = "",
    val templateJsonReceipt: String = ""
)